### ISSUE TITLE
SSH connection issue

### ISSUE THREAD

**Issue by gkadusumilli** [Open-Digital-Twin/framework-fl-testing#2]
Hi  @fschwanck 
Thanks for sharing your work, It's amazing work.
I did local setup with the following steps:

1. Installed Docker desktop
2. In root path of directory >> docker-compose up

However I'm getting the following error "SSH connection error", request to help me
![image](https://github.com/user-attachments/assets/fd8fa9b8-97a1-4b03-af76-f8010a52a958)

**Comment by gkadusumilli** [comment]
![error_fl](https://github.com/user-attachments/assets/e6a66b2a-e103-4a7d-8ab1-d13a3edfa213)

**Comment by gkadusumilli** [comment]
Fixed it.

**Comment by enzolisp** [comment]
> Fixed it.

@gkadusumilli 
I've been getting the same error. How did you fix it? 
Thanks in advance.
